### PR TITLE
Overhauled packaging and testing

### PR DESCRIPTION
**Pull request by agronholm**
- Migrated from `setup.py` to `pyproject.toml`
- Added automated GitHub Action CI based testing
- Migrated publishing workflow to use Trusted Publishing
- Moved test dependencies from `requirements.txt` to `pyproject.toml` (under the `test` extra)
- Removed metadata in `tkreload/__init__.py` as no longer needed (no tools uses these)
- Adopted setuptools_scm to handle versioning (based on git tags) and file inclusion (based on what's in the repository)
- Defined Python 3.9 as the minimum requirement, as the test dependencies won't install on earlier Pythons
- Renamed `README.MD` files to `README.md` for consistency

### CODE REVIEW

**Comment by iamDyeus** [comment]
Thanks for the Contributions @agronholm 🥳

**Comment by agronholm** [comment]
I mistakenly included Python 3.8 in the test workflow; you'll need to delete that. The rest fail because they seem to require a Windows-specific module.

**Comment by agronholm** [comment]
One more thing: you have to configure trusted publishing from the PyPI side too: https://docs.pypi.org/trusted-publishers/adding-a-publisher/

**Comment by iamDyeus** [comment]
> One more thing: you have to configure trusted publishing from the PyPI side too: https://docs.pypi.org/trusted-publishers/adding-a-publisher/

Yeah, I configured that when pushed the v1.0.2 tag.

**Comment by iamDyeus** [comment]
> I mistakenly included Python 3.8 in the test workflow; you'll need to delete that. The rest fail because they seem to require a Windows-specific module.

I'll remove Python 3.8 from the test workflow, will need to look into the Windows-specific module one though.

**Comment by agronholm** [comment]
It seems like you're using `msvcrt` for keyboard handling?

**Comment by iamDyeus** [comment]
I see, we shifted from `keyboard` module to `sys.in` in #6, but I may have accidentally bumped it to `msvcrt` in one of the recent commits.

**Comment by agronholm** [comment]
[This](https://github.com/iamDyeus/tkreload/commit/92c9e783855c74dbcff7ca289385002f4c99be89) is the commit that introduced `msvcrt` to `main.py`.

**Comment by iamDyeus** [comment]
> [This](https://github.com/iamDyeus/tkreload/commit/92c9e783855c74dbcff7ca289385002f4c99be89) is the commit that introduced `msvcrt` to `main.py`.

got it thanks! will fix this soon

**Comment by iamDyeus** [comment]
One more question: you removed the `requirements.txt` in your PR. I was wondering, how are people supposed to run it in a dev environment without a requirements file? Will they need to create a new build every time they try to do something?

**Comment by agronholm** [comment]
No, they'd just install it in editable mode: `pip install -e .[test]`

**Pull request merged**
