### PR TITLE
Tried to solve the auto-reloading functionality issue

### PR DESCRIPTION
**Pull request by danieltayal07**
tried to solve #2 (auto-reload functionality)

couldn't test it sorry because my laptop is acting up and the terminal is not working maybe an os issue 😢 

please try if possible 

if it works properly then please merge it and add hacktoberfest2024 tag i will be grateful

if it doesn't i'll keep trying to contribute after my laptop gets repaired still i will be grateful!

By the way Tkinter Designer is the most useful thing(with respect to me) i have ever came across for especially first year university student like me who is not that up to the mark at python or other coding languages, you have done an amazing, fantastic job.

if not a contributor i will be a proud user !

Thank you for the opportunity to try to add value!

### CODE REVIEW

**Comment by iamDyeus** [comment]
Thank you for the contribution, @danieltayal07!
I'll test it, and if everything looks good, I'll go ahead and merge it.

**Comment by iamDyeus** [comment]
Hey, you'll also need to change `main.py` for the correct implementation of the `auto_reload.py`. Once that's done, I'll check and merge the PR

**Comment by danieltayal07** [comment]
Sure sir 
I will do that by the end of the day and will commit the changes,
Thank you!!

**Comment by danieltayal07** [comment]
main.py changes:

Yeah, hey i uncommented and imported the auto reload functionality code in main.py

Enter + A will enable auto_reload now

status will be displayed of auto_reload hopefully

monitor_file_changes will check for changes if auto_reload enabled

**Comment by iamDyeus** [comment]
I reviewed your commits and noticed there are merge conflicts, likely due to the changes made in #1  If possible, please try resolving them.

**Comment by danieltayal07** [comment]
Yes i'll try to solve it by the end of the day, apologies.
Thanks!

**Comment by iamDyeus** [comment]
Hey, the assigned issue has been resolved in commit 92c9e783855c74dbcff7ca289385002f4c99be89.

You've put in great effort on this issue! If you'd still like to submit a PR, feel free to make a small documentation change, and I'll be happy to merge it.

There’s also plenty of room to find and fix other bugs. Good luck!

**Comment by danieltayal07** [comment]
Thank you much for the opportunity !

I will surely try!

**Pull request closed without merging**
